/*
Copyright The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// EngineImageNodeCapabilitiesApplyConfiguration represents a declarative configuration of the EngineImageNodeCapabilities type for use
// with apply.
//
// EngineImageNodeCapabilities describes the features exposed by one platform
// variant of an engine image on a specific node. Capabilities are role scoped
// because a controller, replica, frontend, and replica disk can have different
// platform requirements even when they use the same image.
type EngineImageNodeCapabilitiesApplyConfiguration struct {
	Controller []string `json:"controller,omitempty"`
	Replica    []string `json:"replica,omitempty"`
	Frontend   []string `json:"frontend,omitempty"`
	Disk       []string `json:"disk,omitempty"`
}

// EngineImageNodeCapabilitiesApplyConfiguration constructs a declarative configuration of the EngineImageNodeCapabilities type for use with
// apply.
func EngineImageNodeCapabilities() *EngineImageNodeCapabilitiesApplyConfiguration {
	return &EngineImageNodeCapabilitiesApplyConfiguration{}
}

// WithController adds the given value to the Controller field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Controller field.
func (b *EngineImageNodeCapabilitiesApplyConfiguration) WithController(values ...string) *EngineImageNodeCapabilitiesApplyConfiguration {
	for i := range values {
		b.Controller = append(b.Controller, values[i])
	}
	return b
}

// WithReplica adds the given value to the Replica field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Replica field.
func (b *EngineImageNodeCapabilitiesApplyConfiguration) WithReplica(values ...string) *EngineImageNodeCapabilitiesApplyConfiguration {
	for i := range values {
		b.Replica = append(b.Replica, values[i])
	}
	return b
}

// WithFrontend adds the given value to the Frontend field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Frontend field.
func (b *EngineImageNodeCapabilitiesApplyConfiguration) WithFrontend(values ...string) *EngineImageNodeCapabilitiesApplyConfiguration {
	for i := range values {
		b.Frontend = append(b.Frontend, values[i])
	}
	return b
}

// WithDisk adds the given value to the Disk field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Disk field.
func (b *EngineImageNodeCapabilitiesApplyConfiguration) WithDisk(values ...string) *EngineImageNodeCapabilitiesApplyConfiguration {
	for i := range values {
		b.Disk = append(b.Disk, values[i])
	}
	return b
}
